#!/bin/bash
set -e

usage()
{
    echo "Usage: $0 <build | clippy | flash>"
    exit 1
}

feat="blue_pill"
tgt="thumbv7m-none-eabi"
chip="STM32F103C8"

flags="--release --no-default-features --features $feat --target $tgt"
case "$1" in
b*)
    set -x
    cargo build $flags
    ;;
c*)
    set -x
    cargo clippy $flags
    ;;
f*)
    set -x
    cargo flash $flags --chip $chip
    ;;
*)
    usage
    ;;
esac
exit 0
# EOF
